#+TITLE: Diazepam

- Diazepam, first marketed as Valium, is a medicine of the benzodiazepine family that typically produces a calming effect.
- It is commonly used to treat a range of conditions including anxiety, alcohol withdrawal syndrome, benzodiazepine withdrawal syndrome, muscle spasms, seizures, trouble sleeping, and restless legs syndrome. 
- It may also be used to cause memory loss during certain medical procedures. 
- It can be taken by mouth, inserted into the rectum, injected into muscle, or injected into a vein. 
  - When given into a vein, effects begin in one to five minutes and last up to an hour. 
  - By mouth, effects may take 40 minutes to begin.
- Common side effects include sleepiness and trouble with coordination. 
  - Serious side effects are rare. 
    - They include suicide, decreased breathing, and an increased risk of seizures if used too frequently in those with epilepsy. 
    - Occasionally excitement or agitation may occur. 
  - Long term use can result in tolerance, dependence, and withdrawal symptoms on dose reduction. 
- Abrupt stopping after long-term use can be potentially dangerous. 
- After stopping, cognitive problems may persist for six months or longer. 
- It is not recommended during pregnancy or breastfeeding. 
- Its mechanism of action is by increasing the effect of the neurotransmitter gamma-aminobutyric acid (GABA).
- Diazepam was first made by Leo Sternbach and commercialized by Hoffmann-La Roche. 
- It has been one of the most frequently prescribed medications in the world since its launch in 1963. 
  - In the United States it was the highest selling medication between 1968 and 1982, selling more than two billion tablets in 1978 alone. 
- In 1985 the patent ended, and there are now more than 500 brands available on the market. 
- Diazepam is on the World Health Organization's List of Essential Medicines, the most effective and safe medicines needed in a health system.
