#+TITLE: Ethylbisiminomethylguaiacol Manganese Chloride

* Background 
- EUK mimics two antioxidant skin enzymes superoxide dismutase (SOD) and catalase

** SOD and Catalase
- superoxide dimutase and catalase are two smart enzymes found in our bodies that speed up the conversion of cell damaging free radicals (such as superoxide radicals) into friendly and harmless things such as water and oxygen
- SOD - is the body's smart antioxidant enzyme that protects the cells from highly reactive, cell-damaging superoxide radicals (O2Å|)
- SOD remains intact during the conversion process and can continue to act as an antioxidant coninually, compared to other anti-oxidants which might be used up during neutralization

* Benefits
- EUK-134 not only prevents damage done by exposure to the sun's harmful UVB rays, but can also increase cell survival after the exposure occurs.
- It is therefore a complete antioxidant system that mimics nature and is safe and beneficial in cosmetics and, more importantly, sunscreens (source).
- UVB-generated oxidative stress contributes to photoaging and photocarcinogenesis, and increased oxidative stress may lead to increased DNA damage, subsequent mutation, and in the long run, cancer.
- By replenishing the cell's antioxidant defense, EUK-134 may be very efficient in the fight against both the short and the long-term photoaging and photocarcinogenesis from UVB radiation on the skin.
- commonly found in Estee Lauder products

