#+TITLE: Exponential Function

* Applications

- compound interest


- e is the limit of 1 plus a small number, raised to the power of the reciprocal of the small number, as that small number approaches 0 
- defined by the limit: $e=\lim_{n \to \infty} (1 + \frac{1}{n})^n$
- in terms of h = 1/n: $e=\lim_{h \to 0} (1 + h)^(1/h)$
- its importance in calculus lies mainly in the fact that the exponential function $y=e^x$ is unchanged by differentiation: $\frac{d(e^x)}{dx}=e^x$, or $\frac{dy}{dx}=y$
- if k is any nonzero constant, all of the functions of $y = c e^{kx}$ are solutions of the differential equation
  - $\frac{dy}{dx} = ky$
- 


* Rules of Exponential Functions

- three basic identities satisfied by exponents
$$x^ax^b = x^{a + b}$$
- identity 1 is always true.
$$x^ay^a = (xy)^a$$
Identity 2 is not always true. For example, if $(x = y = -1)$ and $(a = \frac{1}{2})$, then $(x^ay^a = \sqrt{-1}\sqrt{-1} = i\cdot i = -1)$, whereas $((xy)^a = \sqrt{-1\cdot-1} = \sqrt{1} = 1)$. However, identity 2 is true at least if $(x)$ and $(y)$ are nonnegative and $(a)$ is real (it may also be true under other conditions as well). A common consequence of the failure of identity 2 is that $(\sqrt{x}\sqrt{y} \neq \sqrt{xy})$.
$$(x^a)^b = x^{ab}$$
Identity 3 is not always true. For example, if $(x = -1)$, $(a = 2)$, and $(b = \frac{1}{2})$, then $((x^a)^b = {\left ((-1)^2\right )}^{1/2} = \sqrt{1} = 1)$ and $(x^{ab} = (-1)^{2\cdot1/2} = (-1)^1 = -1)$. However, identity 3 is true at least if $(x)$ is nonnegative or $(b)$ is an integer (again, it may also hold in other cases as well). Two common consequences of the failure of identity 3 are that $(\sqrt{x^2}\neq x)$ and that $(\sqrt{\frac{1}{x}} \neq \frac{1}{\sqrt{x}})$.
