* Pore Types

- classification of pores is not the same thing as classification of adsorbents; an adsorbent usually contains all the listed pore types cite:Bering1966
- the IUPAC provides an useful albeit arbitrary classification of nano-pores (pores with diameters ranging in the order of nanometers) into cite:Sing1985
  * micro-pores (<2nm), 
  * meso-pores (2-50nm), and 
  * macro-pores (>50nm).
- pores may also be classified into open and closed pores based on their access to external fluid cite:Sing1985
- based on their shape, pores may be classified as split, cylindrical, blind, ink-bottle, or funnel shaped pores cite:Sing1985
- cite:Loucks2012 classifies pores in mudrock systems into
  - pores that are  enclosed by the mineral matrix and
  - those contained by the organic matter (kerogens).
  - Whilst pores that are enclosed by the mineral matrix can either be inter-particle or intra-particle, OM pores are solely intra-particle pores.
  - Besides these fracture pores are also a key control on the shale fabric.
- cite:Bering1966 classifies pores into 3 types based on their interaction with adsorptive molecules: 
  - Macropores: Large pores for which the curvature at any point of the surface is negligibly small - smooth surfaces can be regarded as a limiting case of such a structure. The upper and lower limits for the radius of curvature is set at $\infty$ and about 500-1000 A. Capillary condensation occurs only at relative pressures so close to 1, and hence indistinguishable from normal volume condensation. Sufficient to characterize the solid with its surface area ignoring its curvature.
  - Intermediate pores: Both monolayer and multilayer adsorption is accompanied with capillary condensation beyond an easily realized threshold relative pressure. Radius of curvature is between 15 A to about 500-1000 A. Both surface area and curvature need to be considered to characterize the solid.
  - Micropores: Radius of curvature is below 10-15 A. Since adsorption field is prevalent in the entire micropore volume, the concept of surface coverage and mono/multi-layer adsorption lose their meaning. Very difficult to define the concept of surface area for micropores.
    - micro-pore volume is often positively correlated with TOC content of shales suggesting that micropores are more prevalent in organic pores cite:Wang2016
- The size, type, and arrangement of pores can be expected to have a significant effect on the storage and transport characteristics of shales.
- Highly micro-porous coals can be expected to have slower desorption rates compared to meso- and macro- porous coals.
- Pore structure, besides being a key control on gas adsorption and storage, also influences transport and production.
